AWSTemplateFormatVersion: 2010-09-09
Description: |

Resources:
  LogicalID:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "String" # Required
      EnableDnsHostnames: false
      EnableDnsSupport: false
      InstanceTenancy: "String"
      Ipv4IpamPoolId: "String"
      Ipv4NetmaskLength: Number
      Tags:
        Tags
