AWSTemplateFormatVersion: 2010-09-09
Resources:
  # VPCを作成
  TakadaMakeVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.8.0/21
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: TakadaCFTest
  # subnetを作成
  subnetName:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "ap-northeast-1a"
      # VPC作成の論理IDを!Refで指定
      VpcId: !Ref TakadaMakeVPC
      CidrBlock: 10.0.8.0/24
      Tags:
        - Key: Name
          Value: Subnet1FromTakadaCFTest
  # セキュリティグループを作成
  LogicalID:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: TakadaMakeSG
      GroupDescription: "this is security Group"
      # 最上部で定義したVPCの論理IDを指定
      VpcId: !Ref TakadaMakeVPC
      # インバウンドルールを設定
      # https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group.html
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: SGFromTakadaCFTest
